CREATE TABLE question (
    id BIGSERIAL PRIMARY KEY,
    question_text TEXT NOT NULL,
    correct VARCHAR(255) NOT NULL,
    category VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);